### ISSUE TITLE
Add Homebrew support 

### ISSUE THREAD

**Issue by wraybowling** [kevinms/tmux-compose#1]
See https://docs.brew.sh/Formula-Cookbook#homebrew-terminology

**Comment by kevinms** [comment]
I have very little experience with the Mac ecosystem. However, with a cursory reading of the docs you linked I see this:

https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff

> We will reject formulae that seem too obscure, partly because they won’t get maintained and partly because we have to draw the line somewhere.
> 
> We frown on authors submitting their own work unless it is very popular.

I fear tmux-compose is far too obscure of a project to be accepted.

**Comment by wraybowling** [comment]
Yes. Gotta be popular first. Closing
